name: iOS Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Package iOS App
        run: |
          mkdir -p build/ios-artifact/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios-artifact/Payload/Runner.app

          cd build/ios-artifact
          zip -r AI_Camera_unsigned.ipa Payload

      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-app
          path: build/ios-artifact/AI_Camera_unsigned.ipa